### PR TITLE
Update To-Do List Project with Front-End Features and Improved Functionality

### PR DESCRIPTION
**Pull request by LundiLanga**
This pull request introduces several key enhancements and fixes for the To-Do List project, ensuring a better user experience and smoother functionality. Below is a summary of the changes:

**Front-End Enhancements**
**Styling Updates**:

Improved styling for a modern and user-friendly appearance.
Added a background color to make the design visually appealing.
Included a scrollable task list for better task management when the list grows.

**Interactive Features:**

Developed JavaScript functionality for adding, editing, and deleting tasks.
Fixed the "edit task" function to allow seamless inline editing without pop-ups.
Updated icons for editing and deleting tasks for intuitive user interactions.

**Back-End Integration**
**Database Connectivity**:

Connected the project to MongoDB for persistent storage of tasks.
Enabled smooth data passing between the front-end and back-end for task operations.

**Server Enhancements:**

Configured the server to handle dynamic updates for tasks, including adding, editing, and marking tasks as complete.
Documentation Updates

**README Improvements:**

Added a detailed description of the project.
Introduced a "Contact Me" section.
Made subheadings bold for better readability.

Ensured all requested changes, including an updated README and smooth functionality across features, were implemented.
This branch has been reviewed thoroughly and approved by collaborators.

### CODE REVIEW

**Review by Rabianzo — CHANGES_REQUESTED** [review]
Your features are working well. Just remember to add a more detailed README file for your project.

**Review by sidon59 — CHANGES_REQUESTED** [review]
i think everything looks fine. 
i see the deleted files as well
Make sure to add an updated readMe file before merging

**Review by sidon59 — APPROVED** [review]

**Comment by sidon59** [comment]
Looks good.
Add a description for this branch with all changes and resolutions (if any)

**Comment by Rabianzo** [comment]
> Looks good. Add a description for this branch with all changes and resolutions (if any)

I agree. Add details of the pull request to the description.

**Comment by LundiLanga** [comment]
> Looks good. Add a description for this branch with all changes and resolutions (if any)

Alright thanks, I will work on that.

**Comment by LundiLanga** [comment]
> > Looks good. Add a description for this branch with all changes and resolutions (if any)
> 
> I agree. Add details of the pull request to the description.

**Comment by LundiLanga** [comment]
@sidon59 and @Rabianzo I have added content under the Read Me file and the pull request. Please review the changes.

**Review by LawSibisi — COMMENTED** [review]
Changes made look good on my side. just double checking on the whole project to make sure everything is running smoothly.

**Review by Rabianzo — APPROVED** [review]

**Review by sidon59 — APPROVED** [review]
Perfect

**Review by sidon59 — APPROVED** [review]

**Review by LawSibisi — APPROVED** [review]
project looks good on my side

**Review by sidon59 — APPROVED** [review]
perfect

**Pull request merged**
